version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "10:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - mt-inside
  assignees:
  - mt-inside
